/**
 * Regenerates test/fidelity-manifest.json — the per-car record of how closely the
 * engine reproduces the prototype's golden model_output.
 *
 * ⚠ Regenerating this file is a NUMBERS-CHANGE EVENT. The golden test asserts against
 * these allowances; rerunning this script after an engine change will make any drift
 * "pass". Only regenerate deliberately (calibration improvements), never to green a CI.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { costPerMile } from "../src/engine.js";
import type { Constants, Vehicle } from "../src/types.js";

const here = dirname(fileURLToPath(import.meta.url));
const dataPath = join(here, "../../../opencawr_data.json");
const data = JSON.parse(readFileSync(dataPath, "utf8")) as {
  constants: Constants;
  vehicles: (Vehicle & { model_output: Record<string, number> })[];
};

export const GOLDEN_DRAWS = 9000;
export const GOLDEN_SEED = 42;
// margin added on top of today's observed |delta|, absorbing PRNG/quantile jitter
const MARGIN: Record<string, number> = { p50: 0.006, p75: 0.006, p05: 0.006, p90: 0.008, p95: 0.008 };
const METRIC_TO_GOLDEN: Record<string, string> = {
  p50: "cost_per_mile_p50",
  p75: "p75",
  p90: "p90_badluck",
  p05: "band_p05",
  p95: "band_p95",
};

const cars: Record<string, Record<string, number>> = {};
const snapshots: Record<string, number> = {};
const deltas: Record<string, number[]> = { p50: [], p75: [], p90: [], p05: [], p95: [] };

for (const v of data.vehicles) {
  const res = costPerMile(v, data.constants, { draws: GOLDEN_DRAWS, seed: GOLDEN_SEED });
  const allowed: Record<string, number> = {};
  for (const m of Object.keys(METRIC_TO_GOLDEN)) {
    const d = Math.abs(
      (res as unknown as Record<string, number>)[m]! - v.model_output[METRIC_TO_GOLDEN[m]!]!,
    );
    deltas[m]!.push(d);
    allowed[m] = Number((d + MARGIN[m]!).toFixed(4));
  }
  cars[v.name] = allowed;
  // exact determinism snapshot at production draw count
  snapshots[v.name] = costPerMile(v, data.constants, { seed: GOLDEN_SEED }).p50;
}

const mae = Object.fromEntries(
  Object.entries(deltas).map(([k, arr]) => [
    k,
    Number((arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(5)),
  ]),
);

const manifest = {
  README:
    "Per-car allowed |engine − golden| deltas ($/mi). Generated by gen-fidelity-manifest.ts. " +
    "Do not regenerate to make CI pass — see the header of that script.",
  generated: "2026-07-27",
  draws: GOLDEN_DRAWS,
  seed: GOLDEN_SEED,
  fleetMae: mae,
  // ceiling for the aggregate assertion: today's MAE + a small jitter budget
  fleetMaeMax: Object.fromEntries(
    Object.entries(mae).map(([k, v]) => [k, Number(((v as number) + 0.001).toFixed(5))]),
  ),
  cars,
  exactP50Snapshots: snapshots,
};

writeFileSync(join(here, "../test/fidelity-manifest.json"), JSON.stringify(manifest, null, 1));
console.log("fleet MAE:", mae);
console.log(`wrote test/fidelity-manifest.json (${data.vehicles.length} cars)`);
